import type { components } from "./schema"

type Schemas = components["schemas"]

export type PlanDto = Schemas["PlanDto"]
export type FeatureDto = Schemas["FeatureDto"]
export type PlanFeatureRuleDto = Schemas["PlanFeatureRuleDto"]
export type PlanFeatureLinkedDto = Schemas["PlanFeatureLinkedDto"]
export type PlanRevenueResponse = Schemas["PlanRevenueResponse"]
export type CustomerDto = Schemas["CustomerDto"]
export type CustomerBulkResponse = Schemas["CustomerBulkResponse"]
export type CustomerRequest = Schemas["CustomerRequest"]
export type SubscriptionDto = Schemas["SubscriptionDto"]
export type SubscriptionScheduledChangeDto = Schemas["SubscriptionScheduledChangeDto"]
export type InvoiceDto = Schemas["InvoiceDto"]
export type CreditModelDto = Schemas["CreditModelDto"]
export type CreditPoolDto = Schemas["CreditPoolDto"]
export type CreditGrantDto = Schemas["CreditGrantDto"]
export type CreditTransactionDto = Schemas["CreditTransactionDto"]
export type PlanCreditAllocationDto = Schemas["PlanCreditAllocationDto"]
export type EventDto = Schemas["EventDto"]
export type EventGroupDto = Schemas["EventGroupDto"]
export type PagedResponseEventDto = Schemas["PagedResponseEventDto"]
export type AnalyticsResponseDto = Schemas["AnalyticsResponseDto"]
export type RevenueBridgeResponseDto = Schemas["RevenueBridgeResponseDto"]
export type ModelsAnalyticsResponseDto = Schemas["ModelsAnalyticsResponseDto"]
export type AccountSettingDto = Schemas["AccountSettingDto"]
export type AccountApiKeyResponse = Schemas["AccountApiKeyResponse"]
export type JwtResponse = Schemas["JwtResponse"]
