/*
 * Tanso Core - open-source B2B SaaS monetization engine
 * Copyright (C) 2026  Douglas Baek
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.tansoflow.tansocore.application.orchestrator;

import com.stripe.exception.StripeException;
import com.tansoflow.tansocore.entity.AccountSetting;
import com.tansoflow.tansocore.integration.stripe.StripeSyncService;
import com.tansoflow.tansocore.model.api.external.StripeMode;
import com.tansoflow.tansocore.model.event.service.CustomerCreatedEvent;
import com.tansoflow.tansocore.model.event.service.InvoiceCreatedEvent;
import com.tansoflow.tansocore.model.event.service.PlanCreatedEvent;
import com.tansoflow.tansocore.model.event.service.PlanUpdatedEvent;
import com.tansoflow.tansocore.model.event.service.SubscriptionActivatedEvent;
import com.tansoflow.tansocore.model.event.service.SubscriptionCancelledEvent;
import com.tansoflow.tansocore.model.event.service.SubscriptionPlanChangedEvent;
import com.tansoflow.tansocore.repository.AccountSettingRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.event.TransactionPhase;
import org.springframework.transaction.event.TransactionalEventListener;

import java.util.UUID;

@Service
@Slf4j
@RequiredArgsConstructor
public class StripeOrchestrator {
    private final AccountSettingRepository accountSettingRepository;
    private final StripeSyncService stripeSyncService;

    @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)
    public void onInvoiceCreated(InvoiceCreatedEvent event) throws StripeException {
        log.info("Received InvoiceCreatedEvent: invoiceId={}, accountId={}", event.invoiceId(), event.accountId());
        StripeMode mode = getStripeMode(event.accountId());
        if (mode == StripeMode.NONE || mode == StripeMode.STRIPE_DRIVEN) {
            return;
        }

        // Only sync invoices to Stripe in PAYMENT_PASS_THROUGH mode.
        // In STRIPE_INTEGRATION, all invoices (including proration) are auto-generated by Stripe.
        if (mode == StripeMode.PAYMENT_PASS_THROUGH) {
            stripeSyncService.syncNewInvoice(event.invoiceId(), event.accountId());
        }
    }

    @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)
    public void onCustomerCreated(CustomerCreatedEvent event) throws StripeException {
        log.info("Received CustomerCreatedEvent: accountId={}, customerId={}", event.accountId(), event.customerId());
        StripeMode mode = getStripeMode(event.accountId());
        if (mode == StripeMode.NONE) {
            return;
        }

        // Sync customers to Stripe in PAYMENT_PASS_THROUGH, FULL_SYNC, and STRIPE_DRIVEN
        stripeSyncService.createStripeCustomer(event.accountId(), event.customerId());
    }

    @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)
    public void onPlanCreated(PlanCreatedEvent event) throws StripeException {
        log.info("Received PlanCreatedEvent: {}", event);
        StripeMode mode = getStripeMode(event.accountId());
        if (mode == StripeMode.NONE) {
            return;
        }

        if (mode.isStripeIntegration() || mode == StripeMode.STRIPE_DRIVEN) {
            // In STRIPE_INTEGRATION and STRIPE_DRIVEN, create Product + Price in Stripe
            stripeSyncService.createStripeProductWithPrices(event.planId(), event.accountId());
        } else {
            // PAYMENT_PASS_THROUGH: just create the product
            stripeSyncService.createStripeProduct(event.planId().toString(), event.accountId().toString());
        }
    }

    @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)
    public void onPlanUpdated(PlanUpdatedEvent event) throws StripeException {
        log.info("Received PlanUpdatedEvent: {}", event);
        StripeMode mode = getStripeMode(event.accountId());
        if (!mode.isStripeIntegration() && mode != StripeMode.STRIPE_DRIVEN) {
            return;
        }

        // Create a new Stripe Price when plan pricing changes in STRIPE_INTEGRATION or STRIPE_DRIVEN
        stripeSyncService.createStripeProductWithPrices(event.planId(), event.accountId());
    }

    @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)
    public void onSubscriptionActivated(SubscriptionActivatedEvent event) throws StripeException {
        log.info("Received SubscriptionActivatedEvent: {}", event);
        StripeMode mode = getStripeMode(event.accountId());
        if (!mode.isStripeIntegration() && mode != StripeMode.STRIPE_DRIVEN) {
            return;
        }

        stripeSyncService.createStripeSubscription(event.subscriptionId(), event.accountId());
    }

    @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)
    public void onSubscriptionPlanChanged(SubscriptionPlanChangedEvent event) throws StripeException {
        log.info("Received SubscriptionPlanChangedEvent: {}", event);
        StripeMode mode = getStripeMode(event.accountId());
        if (!mode.isStripeIntegration() && mode != StripeMode.STRIPE_DRIVEN) {
            return;
        }

        stripeSyncService.updateStripeSubscriptionPrice(event.subscriptionId(), event.accountId(), event.prorate());
    }

    @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)
    public void onSubscriptionCancelled(SubscriptionCancelledEvent event) throws StripeException {
        log.info("Received SubscriptionCancelledEvent: {}", event);
        StripeMode mode = getStripeMode(event.accountId());
        if (!mode.isStripeIntegration() && mode != StripeMode.STRIPE_DRIVEN) {
            return;
        }

        stripeSyncService.cancelStripeSubscription(event.subscriptionId(), event.accountId(), event.cancelMode());
    }

    private StripeMode getStripeMode(UUID accountId) {
        AccountSetting accountSetting = accountSettingRepository.findAccountSettingById(accountId);
        if (accountSetting == null) {
            return StripeMode.NONE;
        }
        return accountSetting.getStripeMode();
    }
}
