#!/bin/bash
set -euo pipefail

SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "========================================"
echo "  tanso-oss: Full strip pipeline"
echo "========================================"
echo ""

"$SCRIPTS_DIR/strip-secrets.sh"
echo ""
"$SCRIPTS_DIR/strip-crossenv.sh"
echo ""
"$SCRIPTS_DIR/strip-signup-email.sh"
echo ""
"$SCRIPTS_DIR/strip-firebase.sh"
echo ""
"$SCRIPTS_DIR/strip-observe.sh"
echo ""
"$SCRIPTS_DIR/strip-telemetry.sh"
echo ""
"$SCRIPTS_DIR/strip-internal.sh"

echo ""
echo "========================================"
echo "  Strip complete. Manual steps remaining:"
echo "========================================"
echo ""
echo "1. pom.xml: remove firebase-admin and openai dependencies"
echo "2. OnboardingService.java: remove cross-env replication methods"
echo "3. OnboardingController.java: remove internal replication endpoint"
echo "4. AccountController.java: make notification emails configurable"
echo "5. main.ts: remove PostHog/Userback imports and initialization"
echo "6. auth store: remove PostHog identify calls"
echo "7. router.ts: remove analytics/models/sources routes"
echo "8. ExternalClientsConfig.java: remove OpenAI client bean"
echo "9. SideNav.vue: remove analytics/models/sources nav items"
echo "10. application.yaml: add docker profile with env-var-only config"
echo "11. Replace tansohq.com URLs with configurable base URL"
echo "12. Replace hardcoded emails with configurable admin email"
echo "13. Run: gitleaks detect --source . --no-git"
